# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compare_pb2 as compare__pb2


class ComparerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compare = channel.unary_unary(
                '/Compare.Comparer/Compare',
                request_serializer=compare__pb2.CompareRQ.SerializeToString,
                response_deserializer=compare__pb2.CompareRS.FromString,
                )


class ComparerServicer(object):
    """The greeting service definition.
    """

    def Compare(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComparerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compare': grpc.unary_unary_rpc_method_handler(
                    servicer.Compare,
                    request_deserializer=compare__pb2.CompareRQ.FromString,
                    response_serializer=compare__pb2.CompareRS.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Compare.Comparer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comparer(object):
    """The greeting service definition.
    """

    @staticmethod
    def Compare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Compare.Comparer/Compare',
            compare__pb2.CompareRQ.SerializeToString,
            compare__pb2.CompareRS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
