# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compare.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompare.proto\x12\x07\x43ompare\"(\n\tCompareRQ\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0c\n\x04GUID\x18\x02 \x01(\t\"\x1c\n\tCompareRS\x12\x0f\n\x07isEqual\x18\x01 \x01(\x08\x32=\n\x08\x43omparer\x12\x31\n\x07\x43ompare\x12\x12.Compare.CompareRQ\x1a\x12.Compare.CompareRSB\x14\xaa\x02\x11\x43omparisonServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compare_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ComparisonService'
  _COMPARERQ._serialized_start=26
  _COMPARERQ._serialized_end=66
  _COMPARERS._serialized_start=68
  _COMPARERS._serialized_end=96
  _COMPARER._serialized_start=98
  _COMPARER._serialized_end=159
# @@protoc_insertion_point(module_scope)
